NavAdmin: Admin panel
AddPost: Add post
EditPosts: Edit posts
AdminPanel: Admin panel
Post: Post
Posts: Posts
Remove: Remove
Cancel: Cancel
Save: Save
Edit: Edit
Back: Back
Title: Title
FormMissing: Error: Form missing
FormFailure err@Text: Error: #{err}
PostAdded: Post added
NotAdmin: You are not an admin
NotSuperAdmin:  You are not a super admin
AddUser: Add user
Admin: Admin
SuperAdmin: Super admin
Password: Password
Name: Name
Email: Email
UserAdded: User added
Logout: Logout
Login: Login
Users: Users
User: User
UserUpdated: User updated
NotImage: File you were trying to upload is not an image
ImageUploadFailed: Uploading the image failed
Edited: Edited
Update: Update
Modified: modified
Send: Send
Add: Add
EditPost: Edit post
PostEdited: Post edited
DeletePost: Delete post
DeletePostError: Failed to delete the post
Pages: Pages
AddPage: Add page
EditPage: Edit page
PageContent: Page content
Contact: Contact
ResetOriginal: Reset original
VersionHistory: Version history
Version: Version
TopLevel: Top-level page
PageAdded: Page added
ClubMembers: Members
DeletePageError: Failed to delete the page
RestorePage: Restore page
RestorePageError: Failed to restore the page
