NavAdmin: Hallinta
AddPost: Lisää uutinen
EditPosts: Muokkaa uutisia
AdminPanel: Hallinta
Post: Uutinen
Posts: Uutiset
Remove: Poista
Cancel: Peruuta
Save: Tallenna
Edit: Muokkaa
Back: Takaisin
Title: Otsikko
FormMissing: Virhe: Lomake puuttuu
FormFailure err@Text: Virhe: #{err}
PostAdded: Uutinen lisätty
NotAdmin: Et ole ylläpitäjä
NotSuperAdmin:  Et ole pääylläpitäjä
AddUser: Lisää käyttäjä
Admin: Ylläpitäjä
SuperAdmin: Pääylläpitäjä
Password: Salasana
Name: Nimi
Email: Sähköposti
UserAdded: Käyttäjä lisätty
Logout: Kirjaudu ulos
Login: Kirjaudu sisään
Users: Käyttäjät
User: Käyttäjä
UserUpdated: Käyttäjän tiedot päivitetty
NotImage: Tiedosto ei ole kuva
ImageUploadFailed: Kuvan lisäys epäonnistui
Edited: Muokattu
Update: Päivitä
Modified: muokattu
Send: Lähetä
Add: Lisää
EditPost: Muokkaa uutista
PostEdited: Uutinen muokattu
DeletePost: Poista uutinen
DeletePostError: Uutisen poistaminen epäonnistui
Pages: Sivut
AddPage: Lisää sivu
EditPage: Muokkaa sivua
PageContent: Sivun sisältö
Contact: Yhteystiedot
ResetOriginal: Palauta alkuperäinen
VersionHistory: Versiohistoria
Version: Versio
TopLevel: Pääsivu
PageAdded: Sivu lisätty
ClubMembers: Jäsenet
DeletePageError: Sivun poistaminen epäonnistui
RestorePage: Palauta sivu
RestorePageError: Sivun palauttaminen epäonnistui